import { Clock3, Copy, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "./status-badge";
import type { JobStatus } from "@/lib/api/operations";
import { formatDate } from "@/lib/formatting";

export function JobStatusPanel({ job, refreshing, onRefresh }: { job: JobStatus; refreshing: boolean; onRefresh: () => void }) {
  return <section className="border-y bg-white p-5" aria-live="polite"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Clock3 aria-hidden="true" className="size-5 text-[var(--accent)]" /><div><h2 className="font-semibold">Background job</h2><p className="mt-0.5 text-xs text-[var(--muted)]">{job.job_type.replaceAll("_", " ")}</p></div></div><StatusBadge status={job.status} /></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-3"><div><dt className="text-xs text-[var(--muted)]">Attempts</dt><dd className="mt-1 font-semibold">{job.attempt_count} / {job.max_attempts}</dd></div><div><dt className="text-xs text-[var(--muted)]">Started</dt><dd className="mt-1">{formatDate(job.started_at)}</dd></div><div><dt className="text-xs text-[var(--muted)]">Completed</dt><dd className="mt-1">{formatDate(job.completed_at)}</dd></div></dl>{job.error_code ? <div className="mt-4 bg-[var(--danger-soft)] p-3 text-sm text-[var(--danger)]"><strong>{job.error_code}</strong><p className="mt-1">{job.error_message}</p></div> : null}<div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t pt-4"><button type="button" className="flex items-center gap-2 font-mono text-xs text-[var(--muted)] hover:text-[var(--foreground)]" onClick={() => navigator.clipboard.writeText(job.correlation_id)}><Copy className="size-3.5" aria-hidden="true" />Correlation {job.correlation_id.slice(0, 12)}</button><Button variant="secondary" size="sm" onClick={onRefresh} disabled={refreshing}><RefreshCw className={`size-3.5 ${refreshing ? "animate-spin" : ""}`} aria-hidden="true" />Refresh</Button></div></section>;
}
