"use client";

import { useQuery } from "@tanstack/react-query";
import { BarChart3, CheckCircle2, CircleDollarSign, Clock3, Gauge, RefreshCw, Star } from "lucide-react";
import { useState } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ErrorState, LoadingState } from "@/components/feedback/query-state";
import { PageHeader } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { operationsApi, type ImpactFilters } from "@/lib/api/operations";
import { formatCurrency, formatNumber, formatPercent } from "@/lib/formatting";

function Metric({ label, value, detail, icon: Icon }: { label: string; value: string; detail?: string; icon: typeof Gauge }) { return <div className="bg-white p-4"><div className="flex items-center gap-2 text-xs text-[var(--muted)]"><Icon className="size-4" aria-hidden="true" />{label}</div><p className="mt-2 text-xl font-semibold tabular-nums">{value}</p>{detail ? <p className="mt-1 text-xs text-[var(--muted)]">{detail}</p> : null}</div>; }

export function BusinessImpactView() {
  const [draft, setDraft] = useState<ImpactFilters>({});
  const [filters, setFilters] = useState<ImpactFilters>({});
  const query = useQuery({ queryKey: ["business-impact", filters], queryFn: ({ signal }) => operationsApi.filteredImpact(filters, signal) });
  const data = query.data;
  const chart = (data?.series ?? []).map((point, index) => ({ name: String(point.task_type ?? `Task ${index + 1}`), minutes: Number(point.minutes_saved ?? 0), automation: Number(point.automation_rate ?? 0) * 100 }));
  return <div className="space-y-7"><PageHeader title="Business impact" description="Backend-calculated productivity, quality, adoption, and cost. Technical completion and human acceptance remain separate." actions={<Button variant="secondary" onClick={() => query.refetch()} disabled={query.isFetching}><RefreshCw className={`size-4 ${query.isFetching ? "animate-spin" : ""}`} />Refresh</Button>} />
    <form className="grid gap-3 border-y bg-white p-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7" onSubmit={(event) => { event.preventDefault(); setFilters(draft); }}><label className="text-xs font-medium">From<Input type="date" className="mt-1" value={draft.created_from?.slice(0, 10) ?? ""} onChange={(event) => setDraft({ ...draft, created_from: event.target.value ? new Date(`${event.target.value}T00:00:00Z`).toISOString() : undefined })} /></label><label className="text-xs font-medium">To<Input type="date" className="mt-1" value={draft.created_to?.slice(0, 10) ?? ""} onChange={(event) => setDraft({ ...draft, created_to: event.target.value ? new Date(`${event.target.value}T23:59:59Z`).toISOString() : undefined })} /></label>{(["department", "task_type", "provider", "model", "prompt_version_id"] as const).map((field) => <label className="text-xs font-medium capitalize" key={field}>{field.replaceAll("_", " ")}<Input className="mt-1" value={draft[field] ?? ""} onChange={(event) => setDraft({ ...draft, [field]: event.target.value || undefined })} /></label>)}<div className="flex items-end gap-2 xl:col-span-7"><Button type="submit">Apply filters</Button><Button type="button" variant="secondary" onClick={() => { setDraft({}); setFilters({}); }}>Clear</Button></div></form>
    {query.isLoading ? <LoadingState /> : query.error ? <ErrorState error={query.error} retry={() => query.refetch()} /> : data ? <><section className="grid gap-px border bg-[var(--border)] sm:grid-cols-2 lg:grid-cols-4"><Metric label="Completed tasks" value={formatNumber(data.completed_tasks)} icon={BarChart3} /><Metric label="Minutes saved" value={formatNumber(data.total_minutes_saved, 1)} icon={Clock3} /><Metric label="Automation rate" value={formatPercent(data.average_automation_rate)} icon={Gauge} /><Metric label="Technical success" value={formatPercent(data.technical_success_rate)} icon={CheckCircle2} /><Metric label="Human acceptance" value={formatPercent(data.human_acceptance_rate)} detail="Unknown excluded from denominator" icon={CheckCircle2} /><Metric label="First-pass acceptance" value={formatPercent(data.first_pass_acceptance_rate)} icon={CheckCircle2} /><Metric label="Satisfaction" value={`${formatNumber(data.user_satisfaction, 2)} / 5`} icon={Star} /><Metric label="Estimated AI cost" value={formatCurrency(data.total_estimated_cost)} icon={CircleDollarSign} /></section>
      <section className="border-y bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">Minutes saved by completed task</h2><p className="mt-1 text-sm text-[var(--muted)]">Each bar is a backend impact record. Hover values are supplemental to the table below.</p></div><dl className="flex gap-6 text-sm"><div><dt className="text-xs text-[var(--muted)]">Revision rate</dt><dd className="font-semibold">{formatPercent(data.revision_rate)}</dd></div><div><dt className="text-xs text-[var(--muted)]">Error rate</dt><dd className="font-semibold">{formatPercent(data.error_rate)}</dd></div><div><dt className="text-xs text-[var(--muted)]">Use again</dt><dd className="font-semibold">{formatPercent(data.would_use_again_rate)}</dd></div></dl></div>{chart.length ? <><div className="mt-5 h-72" role="img" aria-label="Bar chart of minutes saved for completed tasks"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip /><Bar dataKey="minutes" fill="var(--accent)" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer></div><div className="mt-4 max-h-52 overflow-auto"><table className="w-full text-left text-xs"><caption className="sr-only">Accessible business impact chart data</caption><thead><tr className="border-b"><th className="py-2">Task type</th><th>Minutes saved</th><th>Automation</th></tr></thead><tbody>{chart.map((point, index) => <tr className="border-b" key={`${point.name}-${index}`}><td className="py-2">{point.name}</td><td>{formatNumber(point.minutes, 1)}</td><td>{formatPercent(point.automation / 100)}</td></tr>)}</tbody></table></div></> : <p className="mt-8 border-y py-10 text-center text-sm text-[var(--muted)]">No impact series match these filters.</p>}</section></> : null}
  </div>;
}
