import { Braces, KeyRound, Network, ShieldCheck } from "lucide-react";
import { PageHeader } from "@/components/layout/page-header";

const endpoints = [
  { name: "Campaign workflow", path: "/integrations/n8n/campaigns" },
  { name: "CSV data analysis", path: "/integrations/n8n/data-analysis" },
  { name: "Document processing", path: "/integrations/n8n/document-processing" },
];

export default function N8nPage() { return <div className="space-y-7"><PageHeader title="n8n integrations" description="Server-to-server workflow entry points. The browser documents the contract but never stores or sends webhook secrets." /><section className="grid gap-px border bg-[var(--border)] md:grid-cols-3">{endpoints.map((endpoint) => <article className="bg-white p-5" key={endpoint.path}><Network className="size-5 text-[var(--accent)]" aria-hidden="true" /><h2 className="mt-3 font-semibold">{endpoint.name}</h2><code className="mt-2 block break-all text-xs text-[var(--muted)]">POST {endpoint.path}</code></article>)}</section><section className="grid gap-6 lg:grid-cols-2"><div className="border-y bg-white p-5"><div className="flex items-center gap-2"><KeyRound className="size-5 text-[var(--accent)]" /><h2 className="font-semibold">Required request controls</h2></div><dl className="mt-4 space-y-4 text-sm"><div><dt className="font-mono text-xs">X-Webhook-Secret</dt><dd className="mt-1 text-[var(--muted)]">Configured in n8n credentials and supplied only from the server-side workflow.</dd></div><div><dt className="font-mono text-xs">Idempotency-Key</dt><dd className="mt-1 text-[var(--muted)]">A stable unique key for retries of the same business request.</dd></div><div><dt className="font-mono text-xs">X-Correlation-ID</dt><dd className="mt-1 text-[var(--muted)]">Optional trace key propagated through the backend workflow.</dd></div></dl></div><div className="border-y bg-white p-5"><div className="flex items-center gap-2"><ShieldCheck className="size-5 text-[var(--success)]" /><h2 className="font-semibold">Security boundary</h2></div><p className="mt-4 text-sm leading-6 text-[var(--muted)]">Webhook authentication is independent from interactive user sessions. Provider keys, webhook secrets, actor headers, and privileged backend credentials stay outside browser storage.</p><div className="mt-4 flex items-start gap-2 bg-[var(--accent-soft)] p-3 text-sm"><Braces className="mt-0.5 size-4 shrink-0" /><p>Responses return accepted workflow identifiers and safe status URLs for n8n polling.</p></div></div></section></div>; }
