"""add m7 applied ai platform

Revision ID: 0adb8d1b4a48
Revises: 20260721_0013
Create Date: 2026-07-21 15:37:31.363527
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0adb8d1b4a48"
down_revision: str | None = "20260721_0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "n8n_webhook_receipts",
        sa.Column("receipt_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("signature_hash", sa.String(length=64), nullable=False),
        sa.Column("endpoint", sa.String(length=100), nullable=False),
        sa.Column("correlation_id", sa.String(length=100), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column(
            "response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("receipt_id"),
        sa.UniqueConstraint("idempotency_key", name="uq_n8n_webhook_idempotency"),
        sa.UniqueConstraint("signature_hash", name="uq_n8n_webhook_signature_hash"),
    )
    op.create_index(
        "ix_n8n_webhook_received", "n8n_webhook_receipts", ["received_at"], unique=False
    )
    op.create_table(
        "prompt_templates",
        sa.Column("prompt_template_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("agent_name", sa.String(length=50), nullable=True),
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column(
            "input_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "output_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("prompt_template_id"),
        sa.UniqueConstraint("slug", name="uq_prompt_templates_slug"),
    )
    op.create_index(
        "ix_prompt_templates_task_status",
        "prompt_templates",
        ["task_type", "status"],
        unique=False,
    )
    op.create_table(
        "task_baselines",
        sa.Column("task_baseline_id", sa.UUID(), nullable=False),
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=False),
        sa.Column(
            "manual_duration_minutes", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("manual_steps", sa.Integer(), nullable=False),
        sa.Column(
            "historical_error_rate", sa.Numeric(precision=8, scale=6), nullable=False
        ),
        sa.Column("baseline_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=500), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("baseline_cost >= 0", name="ck_task_baseline_cost"),
        sa.CheckConstraint(
            "historical_error_rate >= 0 AND historical_error_rate <= 1",
            name="ck_task_baseline_error_rate",
        ),
        sa.CheckConstraint(
            "manual_duration_minutes >= 0", name="ck_task_baseline_duration"
        ),
        sa.CheckConstraint("manual_steps >= 0", name="ck_task_baseline_steps"),
        sa.CheckConstraint("sample_size > 0", name="ck_task_baseline_sample"),
        sa.PrimaryKeyConstraint("task_baseline_id"),
    )
    op.create_index(
        "ix_task_baselines_type_department",
        "task_baselines",
        ["task_type", "department"],
        unique=False,
    )
    op.create_table(
        "user_feedback",
        sa.Column("user_feedback_id", sa.UUID(), nullable=False),
        sa.Column("task_run_id", sa.UUID(), nullable=False),
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=True),
        sa.Column("agent_run_id", sa.UUID(), nullable=True),
        sa.Column("prompt_version_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("actor_id", sa.String(length=200), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("helpfulness", sa.Integer(), nullable=False),
        sa.Column("accuracy", sa.Integer(), nullable=False),
        sa.Column("ease_of_use", sa.Integer(), nullable=False),
        sa.Column("accepted_without_editing", sa.Boolean(), nullable=False),
        sa.Column("editing_minutes", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("rework_count", sa.Integer(), nullable=False),
        sa.Column("would_use_again", sa.Boolean(), nullable=False),
        sa.Column("comment", sa.String(length=2000), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("editing_minutes >= 0", name="ck_user_feedback_editing"),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name="ck_user_feedback_rating"),
        sa.CheckConstraint("rework_count >= 0", name="ck_user_feedback_rework"),
        sa.PrimaryKeyConstraint("user_feedback_id"),
        sa.UniqueConstraint(
            "task_run_id", "actor_id", name="uq_user_feedback_task_actor"
        ),
    )
    op.create_index(
        "ix_user_feedback_type_created",
        "user_feedback",
        ["task_type", "created_at"],
        unique=False,
    )
    op.create_table(
        "prompt_versions",
        sa.Column("prompt_version_id", sa.UUID(), nullable=False),
        sa.Column("prompt_template_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("user_prompt_template", sa.Text(), nullable=False),
        sa.Column("variables", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change_summary", sa.String(length=1000), nullable=False),
        sa.Column(
            "model_requirements",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("approved_by", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["prompt_template_id"],
            ["prompt_templates.prompt_template_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("prompt_version_id"),
        sa.UniqueConstraint(
            "prompt_template_id", "version", name="uq_prompt_versions_template_version"
        ),
    )
    op.create_index(
        "ix_prompt_versions_template_status",
        "prompt_versions",
        ["prompt_template_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_prompt_versions_one_active",
        "prompt_versions",
        ["prompt_template_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "applied_workflow_tasks",
        sa.Column("task_run_id", sa.UUID(), nullable=False),
        sa.Column("workflow_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "input_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("input_content", sa.LargeBinary(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("prompt_version_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["background_jobs.job_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.prompt_version_id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("task_run_id"),
    )
    op.create_index(
        "ix_applied_tasks_created",
        "applied_workflow_tasks",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_applied_tasks_type_status",
        "applied_workflow_tasks",
        ["workflow_type", "status"],
        unique=False,
    )
    op.create_table(
        "prompt_experiments",
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("prompt_template_id", sa.UUID(), nullable=False),
        sa.Column("control_version_id", sa.UUID(), nullable=False),
        sa.Column("candidate_version_id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "sample_size > 0", name="ck_prompt_experiments_sample_positive"
        ),
        sa.ForeignKeyConstraint(
            ["candidate_version_id"],
            ["prompt_versions.prompt_version_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["control_version_id"],
            ["prompt_versions.prompt_version_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["evaluation_datasets.dataset_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["prompt_template_id"],
            ["prompt_templates.prompt_template_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("experiment_id"),
    )
    op.create_index(
        "ix_prompt_experiments_template_status",
        "prompt_experiments",
        ["prompt_template_id", "status"],
        unique=False,
    )
    op.create_table(
        "prompt_experiment_results",
        sa.Column("experiment_result_id", sa.UUID(), nullable=False),
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("evaluation_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "control_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "candidate_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("winner", sa.String(length=20), nullable=True),
        sa.Column("decision_reason", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_run_id"],
            ["evaluation_runs.evaluation_run_id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"], ["prompt_experiments.experiment_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("experiment_result_id"),
        sa.UniqueConstraint(
            "experiment_id", name="uq_prompt_experiment_results_experiment"
        ),
    )
    op.create_table(
        "media_assets",
        sa.Column("media_asset_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.String(length=100), nullable=True),
        sa.Column("workflow_id", sa.UUID(), nullable=True),
        sa.Column("task_run_id", sa.UUID(), nullable=True),
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("asset_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("prompt_version_id", sa.UUID(), nullable=True),
        sa.Column("generation_prompt", sa.Text(), nullable=False),
        sa.Column("negative_prompt", sa.Text(), nullable=True),
        sa.Column("storage_uri", sa.String(length=1000), nullable=True),
        sa.Column("thumbnail_uri", sa.String(length=1000), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("safety_status", sa.String(length=50), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_by", sa.String(length=200), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_by", sa.String(length=200), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["campaigns.campaign_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.prompt_version_id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_run_id"], ["applied_workflow_tasks.task_run_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"], ["workflow_runs.workflow_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("media_asset_id"),
    )
    op.create_index(
        "ix_media_assets_campaign", "media_assets", ["campaign_id"], unique=False
    )
    op.create_index(
        "ix_media_assets_status_created",
        "media_assets",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "ai_task_impacts",
        sa.Column("ai_task_impact_id", sa.UUID(), nullable=False),
        sa.Column("task_run_id", sa.UUID(), nullable=False),
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.Column("workflow_id", sa.UUID(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("agent_run_id", sa.UUID(), nullable=True),
        sa.Column("prompt_version_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column(
            "manual_duration_baseline",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
        ),
        sa.Column(
            "ai_duration_minutes", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("minutes_saved", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("steps_before", sa.Integer(), nullable=False),
        sa.Column("steps_after", sa.Integer(), nullable=False),
        sa.Column("automated_steps", sa.Integer(), nullable=False),
        sa.Column("automation_rate", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("output_accepted", sa.Boolean(), nullable=False),
        sa.Column("accepted_without_editing", sa.Boolean(), nullable=False),
        sa.Column("editing_minutes", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("rework_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "automation_rate >= 0 AND automation_rate <= 1",
            name="ck_ai_task_impact_automation_rate",
        ),
        sa.CheckConstraint(
            "minutes_saved >= 0", name="ck_ai_task_impact_minutes_saved"
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"], ["agent_runs.agent_run_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["background_jobs.job_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.prompt_version_id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"], ["workflow_runs.workflow_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("ai_task_impact_id"),
        sa.UniqueConstraint("task_run_id", name="uq_ai_task_impacts_task_run"),
    )
    op.create_index(
        "ix_ai_task_impacts_provider_model",
        "ai_task_impacts",
        ["provider", "model"],
        unique=False,
    )
    op.create_index(
        "ix_ai_task_impacts_type_created",
        "ai_task_impacts",
        ["task_type", "created_at"],
        unique=False,
    )
    op.create_table(
        "media_generation_attempts",
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("media_asset_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("provider_job_id", sa.String(length=300), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["media_asset_id"], ["media_assets.media_asset_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("attempt_id"),
        sa.UniqueConstraint(
            "media_asset_id", "attempt_number", name="uq_media_attempt_number"
        ),
    )
    op.create_table(
        "media_reviews",
        sa.Column("media_review_id", sa.UUID(), nullable=False),
        sa.Column("media_asset_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.String(length=200), nullable=False),
        sa.Column("decision", sa.String(length=50), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("comment", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "rating IS NULL OR rating BETWEEN 1 AND 5", name="ck_media_review_rating"
        ),
        sa.ForeignKeyConstraint(
            ["media_asset_id"], ["media_assets.media_asset_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("media_review_id"),
        sa.UniqueConstraint(
            "media_asset_id", "actor_id", name="uq_media_reviews_asset_actor"
        ),
    )
    op.add_column(
        "agent_runs", sa.Column("prompt_template_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "agent_runs", sa.Column("prompt_version_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "agent_runs", sa.Column("prompt_version_number", sa.Integer(), nullable=True)
    )
    op.add_column(
        "agent_runs",
        sa.Column("prompt_content_hash", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "agent_runs", sa.Column("provider", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "agent_runs",
        sa.Column("model_configuration_hash", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "agent_runs",
        sa.Column("tool_registry_version", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "agent_runs", sa.Column("policy_version", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "agent_runs",
        sa.Column("application_version", sa.String(length=50), nullable=True),
    )
    op.create_foreign_key(
        "fk_agent_runs_prompt_version_id",
        "agent_runs",
        "prompt_versions",
        ["prompt_version_id"],
        ["prompt_version_id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_agent_runs_prompt_template_id",
        "agent_runs",
        "prompt_templates",
        ["prompt_template_id"],
        ["prompt_template_id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_agent_runs_prompt_template_id", "agent_runs", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_agent_runs_prompt_version_id", "agent_runs", type_="foreignkey"
    )
    op.drop_column("agent_runs", "application_version")
    op.drop_column("agent_runs", "policy_version")
    op.drop_column("agent_runs", "tool_registry_version")
    op.drop_column("agent_runs", "model_configuration_hash")
    op.drop_column("agent_runs", "provider")
    op.drop_column("agent_runs", "prompt_content_hash")
    op.drop_column("agent_runs", "prompt_version_number")
    op.drop_column("agent_runs", "prompt_version_id")
    op.drop_column("agent_runs", "prompt_template_id")
    op.drop_table("media_reviews")
    op.drop_table("media_generation_attempts")
    op.drop_index("ix_ai_task_impacts_type_created", table_name="ai_task_impacts")
    op.drop_index("ix_ai_task_impacts_provider_model", table_name="ai_task_impacts")
    op.drop_table("ai_task_impacts")
    op.drop_index("ix_media_assets_status_created", table_name="media_assets")
    op.drop_index("ix_media_assets_campaign", table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_table("prompt_experiment_results")
    op.drop_index(
        "ix_prompt_experiments_template_status", table_name="prompt_experiments"
    )
    op.drop_table("prompt_experiments")
    op.drop_index("ix_applied_tasks_type_status", table_name="applied_workflow_tasks")
    op.drop_index("ix_applied_tasks_created", table_name="applied_workflow_tasks")
    op.drop_table("applied_workflow_tasks")
    op.drop_index(
        "uq_prompt_versions_one_active",
        table_name="prompt_versions",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_index("ix_prompt_versions_template_status", table_name="prompt_versions")
    op.drop_table("prompt_versions")
    op.drop_index("ix_user_feedback_type_created", table_name="user_feedback")
    op.drop_table("user_feedback")
    op.drop_index("ix_task_baselines_type_department", table_name="task_baselines")
    op.drop_table("task_baselines")
    op.drop_index("ix_prompt_templates_task_status", table_name="prompt_templates")
    op.drop_table("prompt_templates")
    op.drop_index("ix_n8n_webhook_received", table_name="n8n_webhook_receipts")
    op.drop_table("n8n_webhook_receipts")
    # ### end Alembic commands ###
