"""harden m7 execution provenance

Revision ID: b6a097aa4b4d
Revises: 20260721_0014
Create Date: 2026-07-21 17:27:58.950395
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b6a097aa4b4d"
down_revision: str | None = "20260721_0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_comparisons",
        sa.Column("comparison_id", sa.UUID(), nullable=False),
        sa.Column("prompt_version_id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("dataset_version", sa.String(length=100), nullable=True),
        sa.Column("providers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("models", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column(
            "execution_settings",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["evaluation_datasets.dataset_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["background_jobs.job_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.prompt_version_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("comparison_id"),
    )
    op.create_index(
        "ix_provider_comparisons_status_created",
        "provider_comparisons",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "prompt_experiment_case_results",
        sa.Column("case_result_id", sa.UUID(), nullable=False),
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("evaluation_case_id", sa.UUID(), nullable=False),
        sa.Column("prompt_version_id", sa.UUID(), nullable=False),
        sa.Column("variant", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_case_id"],
            ["evaluation_cases.evaluation_case_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"], ["prompt_experiments.experiment_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.prompt_version_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("case_result_id"),
        sa.UniqueConstraint(
            "experiment_id",
            "evaluation_case_id",
            "variant",
            name="uq_prompt_experiment_case_variant",
        ),
    )
    op.create_index(
        "ix_prompt_experiment_cases_status",
        "prompt_experiment_case_results",
        ["experiment_id", "status"],
        unique=False,
    )
    op.create_table(
        "provider_comparison_case_results",
        sa.Column("case_result_id", sa.UUID(), nullable=False),
        sa.Column("comparison_id", sa.UUID(), nullable=False),
        sa.Column("evaluation_case_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["comparison_id"],
            ["provider_comparisons.comparison_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_case_id"],
            ["evaluation_cases.evaluation_case_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("case_result_id"),
        sa.UniqueConstraint(
            "comparison_id",
            "evaluation_case_id",
            "provider",
            name="uq_provider_comparison_case_provider",
        ),
    )
    op.create_index(
        "ix_provider_comparison_cases_status",
        "provider_comparison_case_results",
        ["comparison_id", "status"],
        unique=False,
    )
    op.execute(
        "DELETE FROM ai_task_impacts impact "
        "WHERE NOT EXISTS (SELECT 1 FROM applied_workflow_tasks task "
        "WHERE task.task_run_id = impact.task_run_id)"
    )
    op.execute(
        "DELETE FROM user_feedback feedback "
        "WHERE NOT EXISTS (SELECT 1 FROM applied_workflow_tasks task "
        "WHERE task.task_run_id = feedback.task_run_id)"
    )
    op.execute(
        "UPDATE user_feedback feedback SET workflow_id = NULL "
        "WHERE workflow_id IS NOT NULL AND NOT EXISTS "
        "(SELECT 1 FROM workflow_runs workflow "
        "WHERE workflow.workflow_id = feedback.workflow_id)"
    )
    op.execute(
        "UPDATE user_feedback feedback SET prompt_version_id = NULL "
        "WHERE prompt_version_id IS NOT NULL AND NOT EXISTS "
        "(SELECT 1 FROM prompt_versions prompt "
        "WHERE prompt.prompt_version_id = feedback.prompt_version_id)"
    )
    op.execute(
        "UPDATE user_feedback feedback SET agent_run_id = NULL "
        "WHERE agent_run_id IS NOT NULL AND NOT EXISTS "
        "(SELECT 1 FROM agent_runs run "
        "WHERE run.agent_run_id = feedback.agent_run_id)"
    )
    op.create_foreign_key(
        "fk_ai_task_impacts_task_run_id",
        "ai_task_impacts",
        "applied_workflow_tasks",
        ["task_run_id"],
        ["task_run_id"],
        ondelete="RESTRICT",
    )
    op.add_column(
        "applied_workflow_tasks",
        sa.Column("prompt_template_id", sa.UUID(), nullable=True),
    )
    op.add_column(
        "applied_workflow_tasks",
        sa.Column("prompt_version_number", sa.Integer(), nullable=True),
    )
    op.add_column(
        "applied_workflow_tasks",
        sa.Column("prompt_content_hash", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "applied_workflow_tasks",
        sa.Column("model_configuration_hash", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "applied_workflow_tasks",
        sa.Column("application_version", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "applied_workflow_tasks",
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "applied_workflow_tasks", sa.Column("duration_ms", sa.Integer(), nullable=True)
    )
    op.add_column(
        "applied_workflow_tasks",
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "applied_workflow_tasks",
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "applied_workflow_tasks",
        sa.Column(
            "estimated_cost",
            sa.Numeric(precision=14, scale=6),
            server_default="0",
            nullable=False,
        ),
    )
    op.alter_column("applied_workflow_tasks", "input_tokens", server_default=None)
    op.alter_column("applied_workflow_tasks", "output_tokens", server_default=None)
    op.alter_column("applied_workflow_tasks", "estimated_cost", server_default=None)
    op.create_foreign_key(
        "fk_applied_tasks_prompt_template_id",
        "applied_workflow_tasks",
        "prompt_templates",
        ["prompt_template_id"],
        ["prompt_template_id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "media_assets", sa.Column("prompt_template_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "media_assets", sa.Column("prompt_version_number", sa.Integer(), nullable=True)
    )
    op.add_column(
        "media_assets",
        sa.Column("prompt_content_hash", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "media_assets",
        sa.Column("model_configuration_hash", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "media_assets",
        sa.Column("application_version", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "media_assets", sa.Column("error_code", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "media_assets",
        sa.Column("error_message", sa.String(length=2000), nullable=True),
    )
    op.add_column(
        "media_assets",
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_foreign_key(
        "fk_media_assets_prompt_template_id",
        "media_assets",
        "prompt_templates",
        ["prompt_template_id"],
        ["prompt_template_id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "media_generation_attempts",
        sa.Column("provider", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "media_generation_attempts",
        sa.Column("model", sa.String(length=200), nullable=True),
    )
    op.execute(
        "UPDATE media_generation_attempts AS a SET provider = m.provider, model = m.model FROM media_assets AS m WHERE m.media_asset_id = a.media_asset_id"
    )
    op.alter_column("media_generation_attempts", "provider", nullable=False)
    op.alter_column("media_generation_attempts", "model", nullable=False)
    op.add_column(
        "prompt_experiments",
        sa.Column(
            "execution_settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.alter_column("prompt_experiments", "execution_settings", server_default=None)
    op.add_column(
        "prompt_experiments",
        sa.Column(
            "provider", sa.String(length=50), server_default="mock", nullable=False
        ),
    )
    op.add_column(
        "prompt_experiments",
        sa.Column(
            "model",
            sa.String(length=200),
            server_default="mock-applied-ai",
            nullable=False,
        ),
    )
    op.alter_column("prompt_experiments", "provider", server_default=None)
    op.alter_column("prompt_experiments", "model", server_default=None)
    op.add_column(
        "prompt_experiments",
        sa.Column("dataset_version", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "prompt_experiments",
        sa.Column("model_configuration_hash", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "prompt_experiments",
        sa.Column("tool_registry_version", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "prompt_experiments",
        sa.Column("policy_version", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "prompt_experiments",
        sa.Column("application_version", sa.String(length=100), nullable=True),
    )
    op.add_column("prompt_experiments", sa.Column("job_id", sa.UUID(), nullable=True))
    op.add_column(
        "prompt_experiments",
        sa.Column("error_code", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "prompt_experiments",
        sa.Column("error_message", sa.String(length=2000), nullable=True),
    )
    op.create_foreign_key(
        "fk_prompt_experiments_job_id",
        "prompt_experiments",
        "background_jobs",
        ["job_id"],
        ["job_id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_user_feedback_task_run_id",
        "user_feedback",
        "applied_workflow_tasks",
        ["task_run_id"],
        ["task_run_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_user_feedback_workflow_id",
        "user_feedback",
        "workflow_runs",
        ["workflow_id"],
        ["workflow_id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_user_feedback_prompt_version_id",
        "user_feedback",
        "prompt_versions",
        ["prompt_version_id"],
        ["prompt_version_id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_user_feedback_agent_run_id",
        "user_feedback",
        "agent_runs",
        ["agent_run_id"],
        ["agent_run_id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_user_feedback_agent_run_id", "user_feedback", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_user_feedback_prompt_version_id", "user_feedback", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_user_feedback_workflow_id", "user_feedback", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_user_feedback_task_run_id", "user_feedback", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_prompt_experiments_job_id", "prompt_experiments", type_="foreignkey"
    )
    op.drop_column("prompt_experiments", "error_message")
    op.drop_column("prompt_experiments", "error_code")
    op.drop_column("prompt_experiments", "job_id")
    op.drop_column("prompt_experiments", "application_version")
    op.drop_column("prompt_experiments", "policy_version")
    op.drop_column("prompt_experiments", "tool_registry_version")
    op.drop_column("prompt_experiments", "model_configuration_hash")
    op.drop_column("prompt_experiments", "dataset_version")
    op.drop_column("prompt_experiments", "model")
    op.drop_column("prompt_experiments", "provider")
    op.drop_column("prompt_experiments", "execution_settings")
    op.drop_column("media_generation_attempts", "model")
    op.drop_column("media_generation_attempts", "provider")
    op.drop_constraint(
        "fk_media_assets_prompt_template_id", "media_assets", type_="foreignkey"
    )
    op.drop_column("media_assets", "completed_at")
    op.drop_column("media_assets", "error_message")
    op.drop_column("media_assets", "error_code")
    op.drop_column("media_assets", "application_version")
    op.drop_column("media_assets", "model_configuration_hash")
    op.drop_column("media_assets", "prompt_content_hash")
    op.drop_column("media_assets", "prompt_version_number")
    op.drop_column("media_assets", "prompt_template_id")
    op.drop_constraint(
        "fk_applied_tasks_prompt_template_id",
        "applied_workflow_tasks",
        type_="foreignkey",
    )
    op.drop_column("applied_workflow_tasks", "estimated_cost")
    op.drop_column("applied_workflow_tasks", "output_tokens")
    op.drop_column("applied_workflow_tasks", "input_tokens")
    op.drop_column("applied_workflow_tasks", "duration_ms")
    op.drop_column("applied_workflow_tasks", "started_at")
    op.drop_column("applied_workflow_tasks", "application_version")
    op.drop_column("applied_workflow_tasks", "model_configuration_hash")
    op.drop_column("applied_workflow_tasks", "prompt_content_hash")
    op.drop_column("applied_workflow_tasks", "prompt_version_number")
    op.drop_column("applied_workflow_tasks", "prompt_template_id")
    op.drop_constraint(
        "fk_ai_task_impacts_task_run_id", "ai_task_impacts", type_="foreignkey"
    )
    op.drop_index(
        "ix_provider_comparison_cases_status",
        table_name="provider_comparison_case_results",
    )
    op.drop_table("provider_comparison_case_results")
    op.drop_index(
        "ix_prompt_experiment_cases_status", table_name="prompt_experiment_case_results"
    )
    op.drop_table("prompt_experiment_case_results")
    op.drop_index(
        "ix_provider_comparisons_status_created", table_name="provider_comparisons"
    )
    op.drop_table("provider_comparisons")
    # ### end Alembic commands ###
