"use client";

import { useQuery } from "@tanstack/react-query";
import { Activity, Database, HeartPulse, RefreshCw, ServerCog } from "lucide-react";
import { StatusBadge } from "@/components/data-display/status-badge";
import { ErrorState, LoadingState } from "@/components/feedback/query-state";
import { PageHeader } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
import { operationsApi } from "@/lib/api/operations";
import { formatDate } from "@/lib/formatting";

export function SystemHealth() {
  const live = useQuery({ queryKey: ["health"], queryFn: ({ signal }) => operationsApi.health(signal), refetchInterval: 15000 });
  const ready = useQuery({ queryKey: ["readiness"], queryFn: ({ signal }) => operationsApi.readiness(signal), retry: false, refetchInterval: 15000 });
  const summary = useQuery({ queryKey: ["operations-summary"], queryFn: ({ signal }) => operationsApi.summary(signal), refetchInterval: 15000 });
  const refresh = () => { live.refetch(); ready.refetch(); summary.refetch(); };
  return <div className="space-y-7"><PageHeader title="System health" description="Sanitized API, readiness, queue, outbox, worker, and application signals. Secrets and infrastructure addresses are never rendered." actions={<Button variant="secondary" onClick={refresh}><RefreshCw className="size-4" />Refresh</Button>} />{live.isLoading || summary.isLoading ? <LoadingState /> : live.error || summary.error ? <ErrorState error={live.error ?? summary.error} retry={refresh} /> : <><section className="grid gap-px border bg-[var(--border)] sm:grid-cols-2 lg:grid-cols-4"><div className="bg-white p-4"><HeartPulse className="size-5 text-[var(--success)]" /><p className="mt-3 text-xs text-[var(--muted)]">API liveness</p><div className="mt-1"><StatusBadge status={live.data?.status ?? "unavailable"} /></div></div><div className="bg-white p-4"><Database className="size-5 text-[var(--accent)]" /><p className="mt-3 text-xs text-[var(--muted)]">Readiness</p><div className="mt-1"><StatusBadge status={ready.data?.status ?? "unavailable"} /></div></div><div className="bg-white p-4"><Activity className="size-5 text-[var(--accent)]" /><p className="mt-3 text-xs text-[var(--muted)]">Fresh workers</p><p className="mt-1 text-xl font-semibold">{summary.data?.fresh_workers ?? 0}</p></div><div className="bg-white p-4"><ServerCog className="size-5 text-[var(--accent)]" /><p className="mt-3 text-xs text-[var(--muted)]">Application version</p><p className="mt-1 font-mono text-sm font-semibold">{summary.data?.application_version ?? live.data?.version}</p></div></section><section className="grid gap-6 lg:grid-cols-2"><div className="border-y bg-white p-5"><h2 className="font-semibold">Queue states</h2><dl className="mt-4 grid grid-cols-2 gap-4 text-sm">{Object.entries(summary.data?.jobs ?? {}).map(([status, count]) => <div key={status}><dt className="text-xs text-[var(--muted)]">{status}</dt><dd className="mt-1 text-lg font-semibold">{count}</dd></div>)}</dl></div><div className="border-y bg-white p-5"><h2 className="font-semibold">Delivery and alerts</h2><dl className="mt-4 space-y-3 text-sm">{Object.entries(summary.data?.outbox ?? {}).map(([status, count]) => <div className="flex justify-between" key={`outbox-${status}`}><dt className="text-[var(--muted)]">{status} outbox</dt><dd className="font-semibold">{count}</dd></div>)}{Object.entries(summary.data?.alerts ?? {}).map(([status, count]) => <div className="flex justify-between" key={status}><dt className="text-[var(--muted)]">{status} alerts</dt><dd className="font-semibold">{count}</dd></div>)}</dl></div></section>{ready.data?.checks ? <section className="border-y bg-white p-5"><h2 className="font-semibold">Readiness checks</h2><pre className="mt-4 max-h-80 overflow-auto bg-[var(--surface-subtle)] p-4 text-xs leading-6">{JSON.stringify(ready.data.checks, null, 2)}</pre></section> : null}<p className="text-xs text-[var(--muted)]">Last API signal: {formatDate(live.data?.timestamp)}</p></>}</div>;
}
