"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { feedbackApi, type FeedbackCreate } from "@/lib/api/feedback";
import { isApiError } from "@/lib/api/errors";

export const feedbackSchema = z.object({ output_accepted: z.enum(["unknown", "yes", "no"]), accepted_without_editing: z.boolean(), editing_minutes: z.coerce.number().min(0), rework_count: z.coerce.number().int().min(0), rating: z.coerce.number().int().min(1).max(5), helpfulness: z.coerce.number().int().min(1).max(5), accuracy: z.coerce.number().int().min(1).max(5), ease_of_use: z.coerce.number().int().min(1).max(5), would_use_again: z.boolean(), comment: z.string().max(2000).optional() }).superRefine((value, ctx) => { if (value.accepted_without_editing && (value.output_accepted !== "yes" || value.editing_minutes !== 0 || value.rework_count !== 0)) ctx.addIssue({ code: "custom", message: "Accepted without editing requires accepted output, zero editing minutes, and zero rework", path: ["accepted_without_editing"] }); });
type FormInput = z.input<typeof feedbackSchema>;
type Values = z.output<typeof feedbackSchema>;

export function FeedbackForm({ taskId }: { taskId: string }) {
  const client = useQueryClient(); const { register, handleSubmit, formState: { errors } } = useForm<FormInput, unknown, Values>({ resolver: zodResolver(feedbackSchema), defaultValues: { output_accepted: "unknown", accepted_without_editing: false, editing_minutes: 0, rework_count: 0, rating: 4, helpfulness: 4, accuracy: 4, ease_of_use: 4, would_use_again: true, comment: "" } });
  const mutation = useMutation({ mutationFn: (values: Values) => feedbackApi.submit(taskId, { ...values, output_accepted: values.output_accepted === "unknown" ? null : values.output_accepted === "yes", comment: values.comment || null } as FeedbackCreate), onSuccess: () => { toast.success("Feedback submitted"); client.invalidateQueries({ queryKey: ["impact"] }); }, onError: (error) => toast.error(isApiError(error) ? error.message : "Unable to submit feedback") });
  return <form className="border-y bg-white p-5" onSubmit={handleSubmit((values) => mutation.mutate(values))}><h2 className="font-semibold">Human feedback</h2><p className="mt-1 text-sm text-[var(--muted)]">Unknown acceptance is preserved and excluded from the acceptance denominator.</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><label htmlFor="output_accepted" className="mb-1.5 block text-sm font-medium">Output accepted</label><select id="output_accepted" className="min-h-10 w-full rounded-md border bg-white px-3 text-sm" {...register("output_accepted")}><option value="unknown">Not decided</option><option value="yes">Yes</option><option value="no">No</option></select></div><div><label htmlFor="editing_minutes" className="mb-1.5 block text-sm font-medium">Editing minutes</label><Input id="editing_minutes" type="number" min="0" {...register("editing_minutes")} /></div><div><label htmlFor="rework_count" className="mb-1.5 block text-sm font-medium">Rework count</label><Input id="rework_count" type="number" min="0" {...register("rework_count")} /></div><div><label htmlFor="rating" className="mb-1.5 block text-sm font-medium">Overall rating (1-5)</label><Input id="rating" type="number" min="1" max="5" {...register("rating")} /></div><div><label htmlFor="helpfulness" className="mb-1.5 block text-sm font-medium">Helpfulness (1-5)</label><Input id="helpfulness" type="number" min="1" max="5" {...register("helpfulness")} /></div><div><label htmlFor="accuracy" className="mb-1.5 block text-sm font-medium">Accuracy (1-5)</label><Input id="accuracy" type="number" min="1" max="5" {...register("accuracy")} /></div><div><label htmlFor="ease_of_use" className="mb-1.5 block text-sm font-medium">Ease of use (1-5)</label><Input id="ease_of_use" type="number" min="1" max="5" {...register("ease_of_use")} /></div></div><div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="flex min-h-10 items-center gap-2 text-sm"><input type="checkbox" className="size-4 accent-[var(--accent)]" {...register("accepted_without_editing")} />Accepted without editing</label><label className="flex min-h-10 items-center gap-2 text-sm"><input type="checkbox" className="size-4 accent-[var(--accent)]" {...register("would_use_again")} />Would use again</label></div>{errors.accepted_without_editing ? <p className="mt-2 text-xs text-[var(--danger)]">{errors.accepted_without_editing.message}</p> : null}<div className="mt-4"><label htmlFor="feedback-comment" className="mb-1.5 block text-sm font-medium">Comment</label><Textarea id="feedback-comment" {...register("comment")} /></div><div className="mt-4 flex justify-end"><Button type="submit" disabled={mutation.isPending}>{mutation.isPending ? "Submitting..." : "Submit feedback"}</Button></div></form>;
}
