from enum import StrEnum


class UserRole(StrEnum):
    MARKETING = "marketing"
    REVIEWER = "reviewer"
    MANAGER = "manager"
    ADMIN = "admin"
    SYSTEM = "system"


class CampaignStatus(StrEnum):
    RECEIVED = "RECEIVED"
    VALIDATING = "VALIDATING"
    NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"
    ANALYZING = "ANALYZING"
    GENERATING = "GENERATING"
    REVIEWING = "REVIEWING"

    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"

    PENDING_APPROVAL = "PENDING_APPROVAL"
    REVISION_REQUIRED = "REVISION_REQUIRED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"


_ACTIVE_WORKFLOW_STATUS_SEQUENCE = (
    CampaignStatus.RECEIVED,
    CampaignStatus.VALIDATING,
    CampaignStatus.NEEDS_CLARIFICATION,
    CampaignStatus.ANALYZING,
    CampaignStatus.GENERATING,
    CampaignStatus.REVIEWING,
    CampaignStatus.MANUAL_REVIEW_REQUIRED,
    CampaignStatus.PENDING_APPROVAL,
    CampaignStatus.REVISION_REQUIRED,
)

ACTIVE_WORKFLOW_STATUSES: frozenset[CampaignStatus] = frozenset(
    _ACTIVE_WORKFLOW_STATUS_SEQUENCE
)

ACTIVE_WORKFLOW_STATUS_VALUES = tuple(
    status.value for status in _ACTIVE_WORKFLOW_STATUS_SEQUENCE
)


TERMINAL_WORKFLOW_STATUS_VALUES = (
    CampaignStatus.APPROVED.value,
    CampaignStatus.REJECTED.value,
    CampaignStatus.FAILED.value,
)

WORKFLOW_CREATABLE_CAMPAIGN_STATUSES = {
    CampaignStatus.RECEIVED,
    CampaignStatus.REVISION_REQUIRED,
}


class WorkflowStep(StrEnum):
    RECEIVE_CAMPAIGN = "RECEIVE_CAMPAIGN"
    VALIDATE_INPUT = "VALIDATE_INPUT"
    ANALYZE_BRIEF = "ANALYZE_BRIEF"
    GENERATE_CONTENT = "GENERATE_CONTENT"
    REVIEW_CONTENT = "REVIEW_CONTENT"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    COMPLETE = "COMPLETE"


class ApprovalDecision(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    REQUEST_REVISION = "REQUEST_REVISION"


class Platform(StrEnum):
    FACEBOOK = "Facebook"
    TIKTOK = "TikTok"
    DISCORD = "Discord"


class SecurityEventType(StrEnum):
    PROMPT_INJECTION_DETECTED = "PROMPT_INJECTION_DETECTED"
    SENSITIVE_DATA_DETECTED = "SENSITIVE_DATA_DETECTED"
    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"
    INVALID_WEBHOOK_SIGNATURE = "INVALID_WEBHOOK_SIGNATURE"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    OPERATOR_ACTION = "OPERATOR_ACTION"


class SecuritySeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AgentName(StrEnum):
    BRIEF_ANALYST = "BRIEF_ANALYST"
    CONTENT_GENERATOR = "CONTENT_GENERATOR"
    CONTENT_REVIEWER = "CONTENT_REVIEWER"


class AgentRunStatus(StrEnum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    LIMIT_EXCEEDED = "LIMIT_EXCEEDED"


class ToolCallStatus(StrEnum):
    REQUESTED = "REQUESTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REJECTED = "REJECTED"


class PolicyDecision(StrEnum):
    SAFE = "SAFE"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    FORBIDDEN = "FORBIDDEN"


class ActionRequestStatus(StrEnum):
    PROPOSED = "PROPOSED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"


class ActionExecutionStatus(StrEnum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class MemoryRecordStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    PENDING = "PENDING"
    RECORDED = "RECORDED"
    FAILED = "FAILED"


class MemoryType(StrEnum):
    EPISODIC = "EPISODIC"
    OPERATIONAL = "OPERATIONAL"


class MemoryEventType(StrEnum):
    WORKFLOW_RETRY = "WORKFLOW_RETRY"
    REVIEW_FEEDBACK = "REVIEW_FEEDBACK"
    REVISION_COMPLETED = "REVISION_COMPLETED"
    AGENT_FAILED = "AGENT_FAILED"
    ACTION_PROPOSED = "ACTION_PROPOSED"
    POLICY_DECIDED = "POLICY_DECIDED"
    ACTION_APPROVED = "ACTION_APPROVED"
    ACTION_REJECTED = "ACTION_REJECTED"
    ACTION_COMPLETED = "ACTION_COMPLETED"
    ACTION_FAILED = "ACTION_FAILED"
    CAMPAIGN_APPROVAL_DECIDED = "CAMPAIGN_APPROVAL_DECIDED"


class JobType(StrEnum):
    WORKFLOW_RUN = "WORKFLOW_RUN"
    ACTION_EXECUTION = "ACTION_EXECUTION"
    MEMORY_RECONCILIATION = "MEMORY_RECONCILIATION"
    OUTBOX_DISPATCH = "OUTBOX_DISPATCH"
    EVALUATION_RUN = "EVALUATION_RUN"
    ALERT_RECONCILIATION = "ALERT_RECONCILIATION"
    PROMPT_EXPERIMENT_RUN = "PROMPT_EXPERIMENT_RUN"
    PROVIDER_COMPARISON_RUN = "PROVIDER_COMPARISON_RUN"
    IMAGE_GENERATION = "IMAGE_GENERATION"
    DATA_ANALYSIS = "DATA_ANALYSIS"
    DOCUMENT_PROCESSING = "DOCUMENT_PROCESSING"
    VIDEO_STORYBOARD = "VIDEO_STORYBOARD"


class JobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    DEAD_LETTER = "DEAD_LETTER"


class JobAttemptStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class JobErrorClassification(StrEnum):
    RETRYABLE = "RETRYABLE"
    NON_RETRYABLE = "NON_RETRYABLE"


class WorkerStatus(StrEnum):
    STARTING = "STARTING"
    RUNNING = "RUNNING"
    STOPPING = "STOPPING"
    STOPPED = "STOPPED"


class OutboxStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    FAILED = "FAILED"
    DEAD_LETTER = "DEAD_LETTER"


class LeaseUpdateResult(StrEnum):
    UPDATED = "UPDATED"
    NOT_FOUND = "NOT_FOUND"
    INVALID_STATE = "INVALID_STATE"
    LEASE_LOST = "LEASE_LOST"


class OutboxEventType(StrEnum):
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
    WORKFLOW_FAILED = "WORKFLOW_FAILED"
    ACTION_COMPLETED = "ACTION_COMPLETED"
    ACTION_FAILED = "ACTION_FAILED"
    MEMORY_RECONCILIATION_REQUIRED = "MEMORY_RECONCILIATION_REQUIRED"
    EVALUATION_REQUESTED = "EVALUATION_REQUESTED"
    PROMPT_VERSION_ACTIVATED = "PROMPT_VERSION_ACTIVATED"
    PROMPT_EXPERIMENT_COMPLETED = "PROMPT_EXPERIMENT_COMPLETED"
    TASK_IMPACT_RECORDED = "TASK_IMPACT_RECORDED"
    USER_FEEDBACK_RECEIVED = "USER_FEEDBACK_RECEIVED"
    MEDIA_READY_FOR_REVIEW = "MEDIA_READY_FOR_REVIEW"
    MEDIA_APPROVED = "MEDIA_APPROVED"
    MEDIA_REJECTED = "MEDIA_REJECTED"
    DATA_ANALYSIS_COMPLETED = "DATA_ANALYSIS_COMPLETED"
    DOCUMENT_PROCESSING_COMPLETED = "DOCUMENT_PROCESSING_COMPLETED"


class AlertStatus(StrEnum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"


class AlertType(StrEnum):
    WORKFLOW_FAILURE_RATE_HIGH = "WORKFLOW_FAILURE_RATE_HIGH"
    JOB_QUEUE_BACKLOG = "JOB_QUEUE_BACKLOG"
    JOB_DEAD_LETTER = "JOB_DEAD_LETTER"
    ACTION_EXECUTION_FAILURE = "ACTION_EXECUTION_FAILURE"
    MEMORY_RECONCILIATION_BACKLOG = "MEMORY_RECONCILIATION_BACKLOG"
    POSTGRES_UNAVAILABLE = "POSTGRES_UNAVAILABLE"
    MIGRATION_HEAD_MISMATCH = "MIGRATION_HEAD_MISMATCH"
    OUTBOX_BACKLOG = "OUTBOX_BACKLOG"


class EvaluationRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class EvaluationExecutionMode(StrEnum):
    SNAPSHOT = "SNAPSHOT"
    SYSTEM = "SYSTEM"


class EvaluationResultStatus(StrEnum):
    PASSED = "PASSED"
    FAILED = "FAILED"
    ERROR = "ERROR"


class PromptTemplateStatus(StrEnum):
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"


class PromptVersionStatus(StrEnum):
    DRAFT = "DRAFT"
    TESTING = "TESTING"
    APPROVED = "APPROVED"
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"


class PromptExperimentStatus(StrEnum):
    DRAFT = "DRAFT"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class ProviderName(StrEnum):
    MOCK = "mock"
    OPENAI = "openai"
    GEMINI = "gemini"
    ANTHROPIC = "anthropic"


class ProviderComparisonStatus(StrEnum):
    DRAFT = "DRAFT"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class MediaAssetType(StrEnum):
    IMAGE = "IMAGE"
    VIDEO_STORYBOARD = "VIDEO_STORYBOARD"
    VIDEO = "VIDEO"


class MediaAssetStatus(StrEnum):
    REQUESTED = "REQUESTED"
    GENERATING = "GENERATING"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AppliedWorkflowType(StrEnum):
    CAMPAIGN_CONTENT = "CAMPAIGN_CONTENT"
    DATA_ANALYSIS = "DATA_ANALYSIS"
    DOCUMENT_PROCESSING = "DOCUMENT_PROCESSING"
    IMAGE_GENERATION = "IMAGE_GENERATION"
    VIDEO_STORYBOARD = "VIDEO_STORYBOARD"


class AppliedTaskStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


CAMPAIGN_ID_PATTERN = r"^[A-Za-z0-9][A-Za-z0-9_-]*$"

MIN_CAMPAIGN_ID_LENGTH = 3
MAX_CAMPAIGN_ID_LENGTH = 100
MAX_RAW_BRIEF_LENGTH = 20_000
