from enum import StrEnum


class UserRole(StrEnum):
    MARKETING = "marketing"
    REVIEWER = "reviewer"
    MANAGER = "manager"
    ADMIN = "admin"
    SYSTEM = "system"


class CampaignStatus(StrEnum):
    RECEIVED = "RECEIVED"
    VALIDATING = "VALIDATING"
    NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"
    ANALYZING = "ANALYZING"
    GENERATING = "GENERATING"
    REVIEWING = "REVIEWING"

    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"

    PENDING_APPROVAL = "PENDING_APPROVAL"
    REVISION_REQUIRED = "REVISION_REQUIRED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"


_ACTIVE_WORKFLOW_STATUS_SEQUENCE = (
    CampaignStatus.RECEIVED,
    CampaignStatus.VALIDATING,
    CampaignStatus.NEEDS_CLARIFICATION,
    CampaignStatus.ANALYZING,
    CampaignStatus.GENERATING,
    CampaignStatus.REVIEWING,
    CampaignStatus.MANUAL_REVIEW_REQUIRED,
    CampaignStatus.PENDING_APPROVAL,
    CampaignStatus.REVISION_REQUIRED,
)

ACTIVE_WORKFLOW_STATUSES: frozenset[CampaignStatus] = frozenset(
    _ACTIVE_WORKFLOW_STATUS_SEQUENCE
)

ACTIVE_WORKFLOW_STATUS_VALUES = tuple(
    status.value for status in _ACTIVE_WORKFLOW_STATUS_SEQUENCE
)


TERMINAL_WORKFLOW_STATUS_VALUES = (
    CampaignStatus.APPROVED.value,
    CampaignStatus.REJECTED.value,
    CampaignStatus.FAILED.value,
)

WORKFLOW_CREATABLE_CAMPAIGN_STATUSES = {
    CampaignStatus.RECEIVED,
    CampaignStatus.REVISION_REQUIRED,
}


class WorkflowStep(StrEnum):
    RECEIVE_CAMPAIGN = "RECEIVE_CAMPAIGN"
    VALIDATE_INPUT = "VALIDATE_INPUT"
    ANALYZE_BRIEF = "ANALYZE_BRIEF"
    GENERATE_CONTENT = "GENERATE_CONTENT"
    REVIEW_CONTENT = "REVIEW_CONTENT"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    COMPLETE = "COMPLETE"


class ApprovalDecision(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    REQUEST_REVISION = "REQUEST_REVISION"


class Platform(StrEnum):
    FACEBOOK = "Facebook"
    TIKTOK = "TikTok"
    DISCORD = "Discord"


class SecurityEventType(StrEnum):
    PROMPT_INJECTION_DETECTED = "PROMPT_INJECTION_DETECTED"
    SENSITIVE_DATA_DETECTED = "SENSITIVE_DATA_DETECTED"
    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"
    INVALID_WEBHOOK_SIGNATURE = "INVALID_WEBHOOK_SIGNATURE"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"


class SecuritySeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AgentName(StrEnum):
    BRIEF_ANALYST = "BRIEF_ANALYST"
    CONTENT_GENERATOR = "CONTENT_GENERATOR"
    CONTENT_REVIEWER = "CONTENT_REVIEWER"


class AgentRunStatus(StrEnum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    LIMIT_EXCEEDED = "LIMIT_EXCEEDED"


class ToolCallStatus(StrEnum):
    REQUESTED = "REQUESTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REJECTED = "REJECTED"


class PolicyDecision(StrEnum):
    SAFE = "SAFE"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    FORBIDDEN = "FORBIDDEN"


class ActionRequestStatus(StrEnum):
    PROPOSED = "PROPOSED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"


class ActionExecutionStatus(StrEnum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class MemoryRecordStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    PENDING = "PENDING"
    RECORDED = "RECORDED"
    FAILED = "FAILED"


class MemoryType(StrEnum):
    EPISODIC = "EPISODIC"
    OPERATIONAL = "OPERATIONAL"


class MemoryEventType(StrEnum):
    WORKFLOW_RETRY = "WORKFLOW_RETRY"
    REVIEW_FEEDBACK = "REVIEW_FEEDBACK"
    REVISION_COMPLETED = "REVISION_COMPLETED"
    AGENT_FAILED = "AGENT_FAILED"
    ACTION_PROPOSED = "ACTION_PROPOSED"
    POLICY_DECIDED = "POLICY_DECIDED"
    ACTION_APPROVED = "ACTION_APPROVED"
    ACTION_REJECTED = "ACTION_REJECTED"
    ACTION_COMPLETED = "ACTION_COMPLETED"
    ACTION_FAILED = "ACTION_FAILED"
    CAMPAIGN_APPROVAL_DECIDED = "CAMPAIGN_APPROVAL_DECIDED"


CAMPAIGN_ID_PATTERN = r"^[A-Za-z0-9][A-Za-z0-9_-]*$"

MIN_CAMPAIGN_ID_LENGTH = 3
MAX_CAMPAIGN_ID_LENGTH = 100
MAX_RAW_BRIEF_LENGTH = 20_000
